/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        StandardCalculator calc = new StandardCalculator();
        Scanner in = new Scanner(System.in);
        double num1 = in.nextDouble();
        double num2 = in.nextDouble();
        System.out.println(calc.divide(num1,num2));
   // calc.add(1,1);
    System.out.println(calc.getResult());
    //calc.subtract(2, 1);

       //System.out.println(calc.getResult());

       System.out.println(calc.multiply(num1,num2));
       System.out.println(calc.add(num1,num2));
       System.out.println(calc.subtract(num1, num2));

       
    }
}
