/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        double num1;
        double num2;

        System.out.println(new App().getGreeting());
        StandardCalculator calc = new StandardCalculator();
        ScientificCalculator sc = new ScientificCalculator();
   
        Scanner in = new Scanner(System.in);
         num1 = in.nextDouble();
        num2 = in.nextDouble();
        System.out.println(calc.divide(num1,num2));
   // calc.add(1,1);
    System.out.println(calc.getResult());
    //calc.subtract(2, 1);

       //System.out.println(calc.getResult());

     System.out.println(calc.multiply(num1,num2));
     

       System.out.println(calc.subtract(num1, num2));
       //System.out.println(calc.subtract(num1, num2));
    // System.out.println(calc.add(num1,num2));
     

     
          calc.getResult();
          System.out.println(calc.add(num1, num2)); 

          
          System.out.println(sc.cos(3));
          System.out.println(sc.sin(3));
          
          System.out.println(sc.square(3));
          System.out.println(sc.tan(3));
          System.out.println(sc.cbrt(3));
          System.out.println(sc.sqrt(3));
          sc.printResult();

          
    LogicCalculator lcalc = new LogicCalculator();
    lcalc.OR(3,3);
    lcalc.printResult();



         

       
    }
}
